### ISSUE TITLE
编码问题导致错误，奇怪啊，突然就来了，新服务器上面

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/rails-guides-old#37]
``` bash
$ rake generate_guides_CN
/home/ruby/.rvm/rubies/ruby-1.9.3-p194/bin/ruby rails_guides.rb
Generating association_basics.textile as association_basics.html
/data/www/rails-guides/rails_guides/body_converter.rb:28:in `sub!': invalid byte sequence in US-ASCII (ArgumentError)
    from /data/www/rails-guides/rails_guides/body_converter.rb:28:in `set_header_section'
    from /data/www/rails-guides/rails_guides/body_converter.rb:21:in `convert_body'
    from /data/www/rails-guides/rails_guides/generator.rb:165:in `process_body'
    from /data/www/rails-guides/rails_guides/generator.rb:156:in `block in generate_guide'
    from /data/www/rails-guides/rails_guides/generator.rb:147:in `open'
    from /data/www/rails-guides/rails_guides/generator.rb:147:in `generate_guide'
    from /data/www/rails-guides/rails_guides/generator.rb:96:in `block in generate_guides'
    from /data/www/rails-guides/rails_guides/generator.rb:94:in `each'
    from /data/www/rails-guides/rails_guides/generator.rb:94:in `generate_guides'
    from /data/www/rails-guides/rails_guides/generator.rb:47:in `generate'
    from rails_guides.rb:53:in `<main>'
rake aborted!
Command failed with status (1): [/home/ruby/.rvm/rubies/ruby-1.9.3-p194/bin...]

Tasks: TOP => generate_guides_CN
```

**Comment by huacnlee** [comment]
环境问题
